title: "MindOnChain"
description: "my journey through the tech world"
baseurl: "" # Leave empty for user site
url: "https://mmanuelubah.github.io"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-archives

# Author info
author:
  name: mmanuelubah
  avatar: "/assets/images/MindOnChain.png"
  bio: "Writer, Researcher, $hellBoy"

# Collections (optional if you want to group notes)
collections:
  notes:
    output: true
    permalink: /notes/:name/
  books:
    output: true
    permalink: /books/:name/
  ideas:
    output: true
    permalink: /web3/:name/

#tags
tag_archive:
  type: liquid
  path: /tags/

#Category
category_archive:
  type: liquid
  path: /categories/


# Pagination (optional)
paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
highlighter: rouge

#search
search: false
search_provider: lunr

minimal_mistakes_skin: "dark"  # Can be "dark", "default", "contrast", etc.

# Enable the dark/light toggle
color_scheme_toggle: true

# Optional: Choose a default scheme ("light" or "dark")
default_color_scheme: "dark"

include:
  - _pages

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/mmanuelubah"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/mindonchain"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/yourusername"

author_profile: true



