title: "MindOnChain"
description: "my journey through the tech world"
baseurl: "" # Leave empty for user site
url: "https://mmanuelubah.github.io"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-archives

plugins_dir: _plugins

# Author info
author:
  name: mmanuelubah
  avatar: "/assets/images/MindOnChain.png"
  bio: "Writer, Researcher, linux$"
  location: "Lagos, Nigeria"
  links:
    - label: "GitHub"
      icon: "fab fa-github" 
      url: "https://github.com/mmanuelubah"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://x.com/Mind_On_Chain"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/chinaza-ubanatu-05a983184/"
    - label: "Substack"
      icon: "fab fa-substack"
      url: "https://substack.com/@mindonchain"


read_time: true

# Collections (optional if you want to group notes)
collections:
  notes:
    output: true
    permalink: /notes/:title/
  books:
    output: true
    permalink: /books/:title/
  ideas:
    output: true
    permalink: /web3/:title/

#tags
tag_archive:
  type: liquid
  path: /tags/

#Category
category_archive:
  type: liquid
  path: /categories/


# Pagination (optional)
paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
highlighter: rouge

#search
search: false
search_provider: lunr

minimal_mistakes_skin: "dark"  # Can be "dark", "default", "contrast", etc.

# Enable the dark/light toggle
color_scheme_toggle: true

# Optional: Choose a default scheme ("light" or "dark")
default_color_scheme: "dark"

include:
  - _pages
  - _notes
  - _books
  - _web3

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      share: true   # <— Enable sharing buttons
# Social sharing settings
share:
  facebook: true
  twitter: true
  linkedin: true
  substack: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/mmanuelubah"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://x.com/Mind_On_Chain"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/chinaza-ubanatu-05a983184/"
    - label: "Substack"
      icon: "fab fa-substack"
      url: "https://substack.com/@mindonchain"

author_profile: true



